[package]
name = "apinae-lib"
version = "0.0.3"
edition = "2021"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
serde_json = { version = "1.0.138" }
uuid = { version = "1.13.1", features = ["v4"] }
