[package]
name = "apinae-lib"
version = "0.1.5"
edition = "2021"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140" }
uuid = { version = "1.16.0", features = ["v4"] }
dirs = "6.0.0"
