
geekdocToC: 3
geekdocTagsToMenu: true

geekdocRepo: https://github.com/kjetilfjellheim/apinae

geekdocSearch: true
geekdocSearchShowParent: true
geekdocSearchShowDescription: true

geekdocLegalNotice: https://github.com/kjetilfjellheim/apinae/blob/main/LICENSE

geekdocDarkModeDim: true