name: compile-test
on:
  push:
    branches: []
env:
    RUST_BACKTRACE: full
    CARGO_TERM_COLOR: always
jobs:
    build:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4
            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true  
            - name: Install tinyproxy
              run: sudo apt install tinyproxy  
            - name: Install tauri dependencies
              run: sudo apt install -y libwebkit2gtk-4.1-0 libpipewire-0.3-dev build-essential curl wget file openssl libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev pipewire libspa
            - name: Install dependencies
              run: cargo fetch
            - name: Compile
              run: cargo build
            - name: Compile and test
              run: cargo test
            - name: install frontend dependencies
              run: npm install --prefix apinae-ui      
            - name: Build daemon
              run: cargo build --release 
            - name: Build UI
              run: npm run tauri build -- --no-bundle --prefix apinae-ui                     
    outdated:
      name: Outdated
      runs-on: ubuntu-24.04
      timeout-minutes: 45
      steps:
        - uses: actions/checkout@v4
        - uses: dtolnay/rust-toolchain@stable
        - uses: dtolnay/install@cargo-outdated
        - run: cargo outdated -w --exit-code 1
    clippy:
      name: Clippy
      runs-on: ubuntu-24.04
      timeout-minutes: 45
      steps:
        - uses: actions/checkout@v4
        - uses: dtolnay/rust-toolchain@clippy
        - run: cargo clippy -- -Dclippy::all -Dclippy::pedantic
