name: compile-test
on:
  push:
    branches: []
env:
    RUST_BACKTRACE: full
    CARGO_TERM_COLOR: always
jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true  
            - name: Install tinyproxy
              run: sudo apt install tinyproxy  
            - name: Install tauri dependencies                  
              run: |
                sudo apt-get update  
                sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev
            - name: Install dependencies
              run: cargo fetch
            - name: Compile
              run: cargo build
            - name: Compile and test
              run: cargo test -- --test-threads=1
            - name: Install cargo Tauri
              run: cargo install tauri-cli
            - name: install frontend dependencies
              run: npm install --prefix apinae-ui      
            - name: Build daemon
              run: cargo build
            - name: Build UI
              run: cargo tauri build --no-bundle                     
    clippy:
        name: Clippy
        runs-on: ubuntu-22.04
        timeout-minutes: 45
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
            - uses: dtolnay/rust-toolchain@clippy
            - name: Install tauri dependencies                  
              run: |
                sudo apt-get update  
                sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev
            - run: cargo clippy --all-targets --all-features -- -D warnings       
    outdated:
        name: Outdated
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
            - uses: dtolnay/install@cargo-outdated
            - run: cargo outdated -w -R --exit-code 1   
