name: Release
permissions:
  contents: write
on:
  push:
    tags:
      - v[0-9]+.*
jobs:
  create-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
           GITHUB_TOKEN: ${{ github.token }}
      - name: Install tauri dependencies                  
        run: |
          sudo apt-get update  
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev
      - name: Install cargo-edit
        run: cargo install cargo-edit
      - name: Install tinyproxy
        run: sudo apt install tinyproxy            
      - name: Install dependencies
        run: cargo fetch
      - name: Set version
        run: cargo set-version 
      - name: Set version        
        run: |
            VERSION=${{ github.ref_name }}
            cargo set-version ${VERSION#v}
      - name: install frontend dependencies
        run: npm install --prefix apinae-ui      
      - name: Build daemon
        run: cargo build --release 
      - name: Install cargo Tauri
        run: cargo install tauri-cli        
      - name: Build UI
        run: cargo tauri build --no-bundle   
      - name: Upload daemon binary
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./target/release/apinae-daemon
          asset_name: apinae
          asset_content_type: application/octet-stream 
      - name: Upload UI
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./target/release/apinae-ui
          asset_name: apinae-ui
          asset_content_type: application/octet-stream 
